site_name: CivicTechWR Documentation

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - awesome-pages
  - minify
  - git-revision-date-localized

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Policies:
    - Code of Conduct: policies/Code_of_Conduct.md
    - Diversity and Inclusion Policy: policies/Diversity_and_Inclusion_Policy.md
  - FAQ: faq/index.md
  - Guidelines: guidelines/index.md
  - Meeting Minutes: meeting-minutes/index.md
  - Templates: ctwr-templates/index.md
